//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibKRelay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibKRelay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objects&gt;
        ///
        ///&lt;!-- AbyssOfDemons --&gt;
        ///
        ///
        ///   &lt;Object type=&quot;0x0908&quot; id=&quot;Malphas Protector&quot;&gt;
        ///      &lt;Group&gt;Demons&lt;/Group&gt;
        ///      &lt;Enemy/&gt;
        ///      &lt;Class&gt;Character&lt;/Class&gt;
        ///      &lt;AnimatedTexture&gt;
        ///         &lt;File&gt;chars8x8rHero1&lt;/File&gt;
        ///         &lt;Index&gt;0x13&lt;/Index&gt;
        ///      &lt;/AnimatedTexture&gt;
        ///      &lt;HitSound&gt;monster/demons_hit&lt;/HitSound&gt;
        ///      &lt;DeathSound&gt;monster/demons_death&lt;/DeathSound&gt;
        ///      &lt;Size&gt;100&lt;/Size&gt;
        ///      &lt;MaxHitPoints&gt;900&lt;/MaxHitPoints&gt;
        ///      &lt;Defense&gt;7&lt;/Defense&gt;
        ///      &lt;XpMult&gt;0.1&lt;/XpMult&gt;
        ///      &lt;Projectile id=&quot;0&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure:0
        ///CreateSuccess:47
        ///Create:30
        ///PlayerShoot:88
        ///Move:48
        ///PlayerText:64
        ///Text:27
        ///ServerPlayerShoot:68
        ///Damage:9
        ///Update:1
        ///UpdateAck:60
        ///Notification:16
        ///NewTick:23
        ///InvSwap:78
        ///UseItem:100
        ///ShowEffect:80
        ///Hello:36
        ///Goto:33
        ///InvDrop:12
        ///InvResult:18
        ///Reconnect:39
        ///Ping:79
        ///Pong:34
        ///MapInfo:11
        ///Load:49
        ///Pic:57
        ///SetCondition:93
        ///Teleport:58
        ///UsePortal:86
        ///Death:26
        ///Buy:90
        ///BuyResult:10
        ///AoE:94
        ///GroundDamage:46
        ///PlayerHit:28
        ///EnemyHit:21
        ///AoEAck:92
        ///ShootAck:40
        ///OtherHit:50
        ///SquareHit:24
        ///GotoAck:4
        ///Ed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Packets {
            get {
                return ResourceManager.GetString("Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Chars nextCharId=&quot;1&quot; maxNumChars=&quot;1&quot;&gt;&lt;Account&gt;&lt;Credits&gt;40&lt;/Credits&gt;&lt;NextCharSlotPrice&gt;600&lt;/NextCharSlotPrice&gt;&lt;AccountId&gt;-1&lt;/AccountId&gt;&lt;Name&gt;Lauk&lt;/Name&gt;&lt;BeginnerPackageTimeLeft&gt;604800&lt;/BeginnerPackageTimeLeft&gt;&lt;IsAgeVerified&gt;0&lt;/IsAgeVerified&gt;&lt;isFirstDeath /&gt;&lt;Stats&gt;&lt;BestCharFame&gt;0&lt;/BestCharFame&gt;&lt;TotalFame&gt;0&lt;/TotalFame&gt;&lt;Fame&gt;0&lt;/Fame&gt;&lt;/Stats&gt;&lt;/Account&gt;&lt;News&gt;&lt;/News&gt;&lt;Servers&gt;&lt;Server&gt;&lt;Name&gt;USWest&lt;/Name&gt;&lt;DNS&gt;54.153.32.11&lt;/DNS&gt;&lt;Lat&gt;37.34&lt;/Lat&gt;&lt;Long&gt;-121.89&lt;/Long&gt;&lt;Usage&gt;0.00&lt;/Usage&gt;&lt;/Server&gt;&lt;Server&gt;&lt;Name&gt;USMidWest&lt;/N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;GroundTypes&gt;
        ///
        ///&lt;!-- Ground --&gt;
        ///
        ///
        ///   &lt;Ground type=&quot;0x00&quot; id=&quot;Black Water&quot;&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///         &lt;Index&gt;0x09&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;Animate dx=&quot;.5&quot; dy=&quot;.5&quot;&gt;Wave&lt;/Animate&gt;
        ///      &lt;NoWalk/&gt;
        ///      &lt;Speed&gt;1&lt;/Speed&gt;
        ///   &lt;/Ground&gt;
        ///   &lt;Ground type=&quot;0x17&quot; id=&quot;Black Water Light&quot;&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///         &lt;Index&gt;0x0a&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;Animate dx=&quot;0.5&quot; dy=&quot;0.5&quot;&gt;Wave&lt;/Animate&gt;
        ///      &lt;Sink/&gt;
        ///      &lt;B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
    }
}
