//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibKRelay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibKRelay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objects&gt;
        ///  &lt;!--  AbyssOfDemons  --&gt;
        ///  &lt;Object type=&quot;0x0908&quot; id=&quot;Malphas Protector&quot;&gt;
        ///    &lt;Group&gt;Demons&lt;/Group&gt;
        ///    &lt;Enemy/&gt;
        ///    &lt;Class&gt;Character&lt;/Class&gt;
        ///    &lt;AnimatedTexture&gt;
        ///      &lt;File&gt;chars8x8rHero1&lt;/File&gt;
        ///      &lt;Index&gt;0x13&lt;/Index&gt;
        ///    &lt;/AnimatedTexture&gt;
        ///    &lt;HitSound&gt;monster/demons_hit&lt;/HitSound&gt;
        ///    &lt;DeathSound&gt;monster/demons_death&lt;/DeathSound&gt;
        ///    &lt;Size&gt;100&lt;/Size&gt;
        ///    &lt;MaxHitPoints&gt;900&lt;/MaxHitPoints&gt;
        ///    &lt;Defense&gt;7&lt;/Defense&gt;
        ///    &lt;XpMult&gt;0.1&lt;/XpMult&gt;
        ///    &lt;Projectile id=&quot;0&quot;&gt;
        ///      &lt;Obje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure:0
        ///CreateSuccess:21
        ///Create:49
        ///PlayerShoot:52
        ///Move:60
        ///PlayerText:45
        ///Text:23
        ///ServerPlayerShoot:33
        ///Damage:78
        ///Update:96
        ///UpdateAck:89
        ///Notification:104
        ///NewTick:42
        ///InvSwap:46
        ///UseItem:1
        ///ShowEffect:15
        ///Hello:31
        ///Goto:95
        ///InvDrop:6
        ///InvResult:85
        ///Reconnect:16
        ///Ping:84
        ///Pong:83
        ///MapInfo:69
        ///Load:36
        ///Pic:25
        ///SetCondition:3
        ///Teleport:48
        ///UsePortal:86
        ///Death:91
        ///Buy:53
        ///BuyResult:56
        ///AoE:40
        ///GroundDamage:93
        ///PlayerHit:64
        ///EnemyHit:50
        ///AoEAck:61
        ///ShootAck:90
        ///OtherHit:98
        ///SquareHit:77
        ///GotoAck:82
        ///Ed [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Packets {
            get {
                return ResourceManager.GetString("Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Chars nextCharId=&quot;1&quot; maxNumChars=&quot;1&quot;&gt;
        ///  &lt;Account&gt;
        ///    &lt;Credits&gt;40&lt;/Credits&gt;
        ///    &lt;NextCharSlotPrice&gt;600&lt;/NextCharSlotPrice&gt;
        ///    &lt;AccountId&gt;-1&lt;/AccountId&gt;
        ///    &lt;Name&gt;Lauk&lt;/Name&gt;
        ///    &lt;BeginnerPackageTimeLeft&gt;604800&lt;/BeginnerPackageTimeLeft&gt;
        ///    &lt;IsAgeVerified&gt;0&lt;/IsAgeVerified&gt;
        ///    &lt;isFirstDeath /&gt;
        ///    &lt;Stats&gt;
        ///      &lt;BestCharFame&gt;0&lt;/BestCharFame&gt;
        ///      &lt;TotalFame&gt;0&lt;/TotalFame&gt;
        ///      &lt;Fame&gt;0&lt;/Fame&gt;
        ///    &lt;/Stats&gt;
        ///  &lt;/Account&gt;
        ///  &lt;News&gt;&lt;/News&gt;
        ///  &lt;Servers&gt;
        ///    &lt;Server&gt;
        ///      &lt;Name&gt;USWest&lt;/Name&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Servers {
            get {
                return ResourceManager.GetString("Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;GroundTypes&gt;
        ///  &lt;!--  Ground  --&gt;
        ///  &lt;Ground type=&quot;0x00&quot; id=&quot;Black Water&quot;&gt;
        ///    &lt;Texture&gt;
        ///      &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///      &lt;Index&gt;0x09&lt;/Index&gt;
        ///    &lt;/Texture&gt;
        ///    &lt;Animate dx=&quot;.5&quot; dy=&quot;.5&quot;&gt;Wave&lt;/Animate&gt;
        ///    &lt;NoWalk/&gt;
        ///    &lt;Speed&gt;1&lt;/Speed&gt;
        ///  &lt;/Ground&gt;
        ///  &lt;Ground type=&quot;0x17&quot; id=&quot;Black Water Light&quot;&gt;
        ///    &lt;Texture&gt;
        ///      &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///      &lt;Index&gt;0x0a&lt;/Index&gt;
        ///    &lt;/Texture&gt;
        ///    &lt;Animate dx=&quot;0.5&quot; dy=&quot;0.5&quot;&gt;Wave&lt;/Animate&gt;
        ///    &lt;Sink/&gt;
        ///    &lt;BlendPriority&gt;2&lt;/BlendPriority&gt;
        ///    &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
    }
}
