//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reconnect {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class ReconnectSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ReconnectSettings defaultInstance = ((ReconnectSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ReconnectSettings())));
        
        public static ReconnectSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastRealmData {
            get {
                return ((string)(this["LastRealmData"]));
            }
            set {
                this["LastRealmData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDungeonData {
            get {
                return ((string)(this["LastDungeonData"]));
            }
            set {
                this["LastDungeonData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-5;Vault")]
        public string VaultData {
            get {
                return ((string)(this["VaultData"]));
            }
            set {
                this["VaultData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuildHallData {
            get {
                return ((string)(this["GuildHallData"]));
            }
            set {
                this["GuildHallData"] = value;
            }
        }
    }
}
