//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LootHelper {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LootHelperConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static LootHelperConfig defaultInstance = ((LootHelperConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LootHelperConfig())));
        
        public static LootHelperConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootNotifications {
            get {
                return ((bool)(this["LootNotifications"]));
            }
            set {
                this["LootNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLoot {
            get {
                return ((bool)(this["AutoLoot"]));
            }
            set {
                this["AutoLoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Health Potion, Mana Potion, Potion of Life, Potion of Mana, Potion of Dex, Potion" +
            " of Dexterity, Potion of Vitality, Potion of Defense, Potion of Speed, Potion of" +
            " Wisdom")]
        public string AutoLootList {
            get {
                return ((string)(this["AutoLootList"]));
            }
            set {
                this["AutoLootList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LootQuests {
            get {
                return ((bool)(this["LootQuests"]));
            }
            set {
                this["LootQuests"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color NotificationColor {
            get {
                return ((global::System.Drawing.Color)(this["NotificationColor"]));
            }
            set {
                this["NotificationColor"] = value;
            }
        }
    }
}
