//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapFilter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MapFilterConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static MapFilterConfig defaultInstance = ((MapFilterConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MapFilterConfig())));
        
        public static MapFilterConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Ice Slide=&gt;Gold Tile</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TileFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TileFilters"]));
            }
            set {
                this["TileFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Blue Sprite Tree=&gt;None</string>
  <string>White Sprite Tree=&gt;None</string>
  <string>Green Sprite Tree=&gt;None</string>
  <string>Red Sprite Tree=&gt;None</string>
  <string>Purple Sprite Tree=&gt;None</string>
  <string>Yellow Sprite Tree=&gt;None</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ObjectFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ObjectFilters"]));
            }
            set {
                this["ObjectFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enabled {
            get {
                return ((bool)(this["Enabled"]));
            }
            set {
                this["Enabled"] = value;
            }
        }
    }
}
