//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_K_Relay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib_K_Relay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objects&gt;
        ///
        ///
        ///
        ///   &lt;Object type=&quot;0x0e56&quot; id=&quot;Masked Party God&quot;&gt;
        ///      &lt;Enemy/&gt;
        ///      &lt;Class&gt;Character&lt;/Class&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiObjBig&lt;/File&gt;
        ///         &lt;Index&gt;0x40&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;AltTexture id=&quot;1&quot;&gt;
        ///         &lt;Texture&gt;
        ///            &lt;File&gt;lofiObjBig&lt;/File&gt;
        ///            &lt;Index&gt;0x41&lt;/Index&gt;
        ///         &lt;/Texture&gt;
        ///      &lt;/AltTexture&gt;
        ///      &lt;AltTexture id=&quot;2&quot;&gt;
        ///         &lt;Texture&gt;
        ///            &lt;File&gt;lofiObjBig&lt;/File&gt;
        ///            &lt;Index&gt;0x42&lt;/Index&gt;
        ///         &lt;/Texture&gt;
        ///      &lt;/AltTexture&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompleteGamedata {
            get {
                return ResourceManager.GetString("CompleteGamedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot;?&gt;&lt;Objects&gt;
        ///   &lt;Object id=&quot;Masked Party God&quot; type=&quot;0x0e56&quot;&gt;
        ///      &lt;Enemy/&gt;
        ///      &lt;Class&gt;Character&lt;/Class&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiObjBig&lt;/File&gt;
        ///         &lt;Index&gt;0x40&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;AltTexture id=&quot;1&quot;&gt;
        ///         &lt;Texture&gt;
        ///            &lt;File&gt;lofiObjBig&lt;/File&gt;
        ///            &lt;Index&gt;0x41&lt;/Index&gt;
        ///         &lt;/Texture&gt;
        ///      &lt;/AltTexture&gt;
        ///      &lt;AltTexture id=&quot;2&quot;&gt;
        ///         &lt;Texture&gt;
        ///            &lt;File&gt;lofiObjBig&lt;/File&gt;
        ///            &lt;Index&gt;0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Enemies {
            get {
                return ResourceManager.GetString("Enemies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot;?&gt;&lt;Objects&gt;
        ///   &lt;Object id=&quot;Common Feline Egg&quot; type=&quot;0xc85&quot;&gt;
        ///      &lt;Class&gt;Equipment&lt;/Class&gt;
        ///      &lt;Item/&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiObj2&lt;/File&gt;
        ///         &lt;Index&gt;0x100&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;SlotType&gt;26&lt;/SlotType&gt;
        ///      &lt;Tier&gt;0&lt;/Tier&gt;
        ///      &lt;Description&gt;{equip.A_common_feline_pet_egg.}&lt;/Description&gt;
        ///      &lt;PetFamily&gt;Feline&lt;/PetFamily&gt;
        ///      &lt;Rarity&gt;Common&lt;/Rarity&gt;
        ///      &lt;Activate&gt;CreatePet&lt;/Activate&gt;
        ///      &lt;Consumable/&gt;
        ///      &lt;BagType&gt;3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot;?&gt;&lt;Objects&gt;
        ///   &lt;Object id =&quot;None&quot; type=&quot;0x0&quot;&gt;
        ///   &lt;/Object&gt;
        ///   &lt;Object id=&quot;Tree A&quot; type=&quot;0x0100&quot;&gt;
        ///      &lt;Class&gt;GameObject&lt;/Class&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment&lt;/File&gt;
        ///         &lt;Index&gt;0x49&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;HitSound&gt;monster/trees_hit&lt;/HitSound&gt;
        ///      &lt;DeathSound&gt;monster/tress_death&lt;/DeathSound&gt;
        ///      &lt;MaxHitPoints&gt;1000&lt;/MaxHitPoints&gt;
        ///      &lt;MinSize&gt;130&lt;/MinSize&gt;
        ///      &lt;MaxSize&gt;160&lt;/MaxSize&gt;
        ///      &lt;SizeStep&gt;5&lt;/SizeStep&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Packets&gt;
        ///	&lt;Packet&gt;
        ///	&lt;PacketName&gt;FAILURE&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;0&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;CREATESUCCESS&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;86&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;CREATE&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;90&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;PLAYERSHOOT&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;16&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;MOVE&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;14&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;PLAYERTEXT&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;67&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;TEX [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Packets {
            get {
                return ResourceManager.GetString("Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;GroundTypes&gt;
        ///
        ///
        ///
        ///   &lt;Ground type=&quot;0x00&quot; id=&quot;Black Water&quot;&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///         &lt;Index&gt;0x09&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;Animate dx=&quot;.5&quot; dy=&quot;.5&quot;&gt;Wave&lt;/Animate&gt;
        ///      &lt;NoWalk/&gt;
        ///      &lt;Speed&gt;1&lt;/Speed&gt;
        ///   &lt;/Ground&gt;
        ///   &lt;Ground type=&quot;0x17&quot; id=&quot;Black Water Light&quot;&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///         &lt;Index&gt;0x0a&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;Animate dx=&quot;0.5&quot; dy=&quot;0.5&quot;&gt;Wave&lt;/Animate&gt;
        ///      &lt;Sink/&gt;
        ///      &lt;BlendPriority&gt;2&lt;/BlendPriority&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
    }
}
