//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_K_Relay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lib_K_Relay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objects&gt;
        ///
        ///&lt;!-- AbyssOfDemons --&gt;
        ///
        ///
        ///   &lt;Object type=&quot;0x0908&quot; id=&quot;Malphas Protector&quot;&gt;
        ///      &lt;Group&gt;Demons&lt;/Group&gt;
        ///      &lt;Enemy/&gt;
        ///      &lt;Class&gt;Character&lt;/Class&gt;
        ///      &lt;AnimatedTexture&gt;
        ///         &lt;File&gt;chars8x8rHero1&lt;/File&gt;
        ///         &lt;Index&gt;0x13&lt;/Index&gt;
        ///      &lt;/AnimatedTexture&gt;
        ///      &lt;HitSound&gt;monster/demons_hit&lt;/HitSound&gt;
        ///      &lt;DeathSound&gt;monster/demons_death&lt;/DeathSound&gt;
        ///      &lt;Size&gt;100&lt;/Size&gt;
        ///      &lt;MaxHitPoints&gt;900&lt;/MaxHitPoints&gt;
        ///      &lt;Defense&gt;7&lt;/Defense&gt;
        ///      &lt;XpMult&gt;0.1&lt;/XpMult&gt;
        ///      &lt;Projectile id=&quot;0&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Packets&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;FAILURE&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;0&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;CREATESUCCESS&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;86&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;CREATE&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;90&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;PLAYERSHOOT&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;16&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;MOVE&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;14&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt;Packet&gt;
        ///	&lt;PacketName&gt;PLAYERTEXT&lt;/PacketName&gt;
        ///	&lt;PacketID&gt;67&lt;/PacketID&gt;
        ///&lt;/Packet&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Packets {
            get {
                return ResourceManager.GetString("Packets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;GroundTypes&gt;
        ///
        ///&lt;!-- Ground --&gt;
        ///
        ///
        ///   &lt;Ground type=&quot;0x00&quot; id=&quot;Black Water&quot;&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///         &lt;Index&gt;0x09&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;Animate dx=&quot;.5&quot; dy=&quot;.5&quot;&gt;Wave&lt;/Animate&gt;
        ///      &lt;NoWalk/&gt;
        ///      &lt;Speed&gt;1&lt;/Speed&gt;
        ///   &lt;/Ground&gt;
        ///   &lt;Ground type=&quot;0x17&quot; id=&quot;Black Water Light&quot;&gt;
        ///      &lt;Texture&gt;
        ///         &lt;File&gt;lofiEnvironment2&lt;/File&gt;
        ///         &lt;Index&gt;0x0a&lt;/Index&gt;
        ///      &lt;/Texture&gt;
        ///      &lt;Animate dx=&quot;0.5&quot; dy=&quot;0.5&quot;&gt;Wave&lt;/Animate&gt;
        ///      &lt;Sink/&gt;
        ///      &lt;BlendPriority&gt;2&lt;/Blend [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
    }
}
