//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartialGodmode {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class PartialGodmodeConfig : global::System.Configuration.ApplicationSettingsBase {
        
        private static PartialGodmodeConfig defaultInstance = ((PartialGodmodeConfig)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PartialGodmodeConfig())));
        
        public static PartialGodmodeConfig Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OnByDefault {
            get {
                return ((bool)(this["OnByDefault"]));
            }
            set {
                this["OnByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockPlayerHit {
            get {
                return ((bool)(this["BlockPlayerHit"]));
            }
            set {
                this["BlockPlayerHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockSquareHit {
            get {
                return ((bool)(this["BlockSquareHit"]));
            }
            set {
                this["BlockSquareHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockOtherHit {
            get {
                return ((bool)(this["BlockOtherHit"]));
            }
            set {
                this["BlockOtherHit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NumberOfHitsBeforeBlock {
            get {
                return ((int)(this["NumberOfHitsBeforeBlock"]));
            }
            set {
                this["NumberOfHitsBeforeBlock"] = value;
            }
        }
    }
}
